name: auth
description: Auth Keycloak
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=2.19.5 <3.0.0'}
dependencies:
  flutter: {sdk: flutter}
  cupertino_icons: ^1.0.2
  openid_client: ^0.4.7
  url_launcher: ^6.1.14
  jwt_decoder: ^2.0.1
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  dio: ^5.5.0+1
  dio_http_cache_fix: ^0.5.1
dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets: [assets/env/]
  fonts: []
